# Generated by Django 5.2.6 on 2025-09-12 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='وصف الفئة')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فئة',
                'verbose_name_plural': 'الفئات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'محافظة',
                'verbose_name_plural': 'المحافظات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الإعلان')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('description', models.TextField(verbose_name='وصف الإعلان')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('condition', models.CharField(choices=[('new', 'جديد'), ('used_excellent', 'مستعمل - ممتاز'), ('used_good', 'مستعمل - جيد'), ('used_fair', 'مستعمل - مقبول')], default='used_good', max_length=20, verbose_name='حالة المنتج')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('sold', 'مباع'), ('expired', 'منتهي الصلاحية')], default='active', max_length=20, verbose_name='حالة الإعلان')),
                ('contact_phone', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('image', models.ImageField(blank=True, upload_to='advertisements/%Y/%m/%d/', verbose_name='صورة المنتج')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL, verbose_name='البائع')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='marketplace.category', verbose_name='الفئة')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.governorate', verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'الإعلانات',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('body', models.TextField(verbose_name='نص الرسالة')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='marketplace.advertisement')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['-created'], name='marketplace_created_7828ef_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['status'], name='marketplace_status_258cf4_idx'),
        ),
    ]
